# Generated by Django 5.2.17 on 2026-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='question',
            field=models.CharField(choices=[('general', 'General question'), ('sizing', 'Sizing help'), ('resole', 'Resole service'), ('order', 'Order status'), ('press', 'Press & wholesale')], max_length=100),
        ),
    ]
